version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
  redis:
    image: redis
    command: "redis-server --requirepass django_password"
    ports:
      - "6379:6379"